version: '3'
services:
  # backend api
  node-docker-api:
    container_name: backend
    #image: node:14.0.1
    build: ./
    command: npm start
    working_dir: /usr/src/node-docker
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/node-docker
    environment:
      REDIS_URI: redis://redis:6379
    links:
      - redis

  # Redis services
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
