const staions = [
  'DILSHAD GARDEN ***',
  'SHAHDARA',
  'SEELAMPUR',
  'ROHINI WEST',
  'RITHALA',
  'PITAMPURA',
  'SHASTRI NAGAR',
  'ROHINI EAST',
  'TIS HAZARI',
  'RAJIV CHOWK',
  'NEW DELHI (DMRC)',
  'KASHMERE GATE',
  'JAHANGIR PURI',
  'GTB NAGAR',
  'CHANDNI CHOWK',
  'CHWARI BAZAR',
  'PATEL CHOWK',
  'AIIMS',
  'GREEN PARK',
  'HAUZ KHAS',
  'MALVIYA NAGAR',
  'SAKET',
  'CHATTARPUR',
  'MG ROAD',
  'HUDA CITY CENTER',
  'VISHWAVIDYALAYA',
  'IFFCO CHOWK',
  'SIKANDERPUR',
  'AZADPUR',
  'KASHMERE GATE',
  'PRAGATI MAIDAN',
  'INA',
  'DWARKA MOR',
  'NAWADA',
  'UTTAM NAGAR WEST',
  'UTTAM NAGAR EAST',
  'JANAKPURI WEST',
  'JANAKPURI EAST',
  'TILAK NAGAR',
  'SUBHASH NAGAR',
  'RAJOURI GARDEN',
  'MOTI NAGAR',
  'SHADIPUR',
  'RAJENDRA PLACE',
  'KAROL BAGH',
  'JHANDEWALAN',
  'R K ASHRAM MARG',
  'BARAKHAMBA ROAD',
  'MAVUR VIHAR PHASE 1',
  'NOIDA SECTOR -15',
  'NOIDA SECTOR -18',
  'BOTANICAL GARDEN',
  'NOIDA CITY CENTRE',
  'AKSHARDHAM',
  'TAGORE GARDEN',
  'NOIDA SEC 16',
  'PATEL NAGAR',
  'NEW ASHOK NAGAR',
  'LAXMI NAGAR',
  'KAUSHAMBI',
  'VAISHALI',
  'NIRMAN VIHAR',
  'PREET VIHAR',
  'NANGLOI',
  'GOVINDPURI',
  'BADARPUR',
  'NEHRU PLACE',
  'BARAKHAMBA METRO STATION',
  'NEW DELHIAIRPORT LINE',
  'SHIVAJI STADIUM',
  'DHAULA KUAN',
  'DELHI AEROCITY',
  'IGI AIRPORT',
  'DWARKA SEC 21 AIRPORT LINE',
];

let abc = 'Seeder value of redis';

const redis = require('redis');
const client = redis.createClient(process.env.REDIS_URI);

if (process.argv[2] === '-i') {
  client.set('stations', JSON.stringify(staions), (err, data) => {
    console.log('Redis seeder completes');
  });
  client.set('abc', abc, (err, data) => {
    console.log('Redis seeder completes');
  });
}
