FROM redis:6.0.1

#RUN node seeder -i
#RUN /usr/bin/redis-server /etc/redis.conf
#RUN redis-server /usr/local/etc/redis.conf 

#COPY redis.conf /usr/local/etc/redis/redis.conf
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#CMD [ "redis-server", "set", "station", "STATIONTEXT" ]

# RUN set station 11112222333344455

#ARG REDIS_TEST=REDISSEEDING

#ENV REDIS-KEY=${REDIS_TEST}

